/* Generated by scripts/assemble-condition-audio.py. Eight conditions enable together. */
window.STUDY_AUDIO_VERSION="condition-narration-2026-09-23-v1";
window.STUDY_AUDIO={
  "natural": {
    "none": {
      "src": "./audio/recordings/natural-none-0923.mp3",
      "duration": 142.157,
      "cues": [
        {
          "start": 0.324,
          "end": 8.015
        },
        {
          "start": 8.789,
          "end": 39.969
        },
        {
          "start": 39.969,
          "end": 71.829
        },
        {
          "start": 72.329,
          "end": 100.409
        },
        {
          "start": 100.409,
          "end": 121.449
        },
        {
          "start": 121.449,
          "end": 141.989
        }
      ]
    },
    "procedural": {
      "src": "./audio/recordings/natural-procedural-0923.mp3",
      "duration": 142.94,
      "cues": [
        {
          "start": 0.274,
          "end": 8.812
        },
        {
          "start": 9.572,
          "end": 40.752
        },
        {
          "start": 40.752,
          "end": 72.612
        },
        {
          "start": 73.112,
          "end": 101.192
        },
        {
          "start": 101.192,
          "end": 122.232
        },
        {
          "start": 122.232,
          "end": 142.772
        }
      ]
    },
    "substantive": {
      "src": "./audio/recordings/natural-substantive-0923.mp3",
      "duration": 144.877,
      "cues": [
        {
          "start": 0.261,
          "end": 10.769
        },
        {
          "start": 11.509,
          "end": 42.689
        },
        {
          "start": 42.689,
          "end": 74.549
        },
        {
          "start": 75.049,
          "end": 103.129
        },
        {
          "start": 103.129,
          "end": 124.169
        },
        {
          "start": 124.169,
          "end": 144.709
        }
      ]
    },
    "decisional": {
      "src": "./audio/recordings/natural-decisional-0923.mp3",
      "duration": 144.282,
      "cues": [
        {
          "start": 0.241,
          "end": 10.31
        },
        {
          "start": 10.914,
          "end": 42.094
        },
        {
          "start": 42.094,
          "end": 73.954
        },
        {
          "start": 74.454,
          "end": 102.534
        },
        {
          "start": 102.534,
          "end": 123.574
        },
        {
          "start": 123.574,
          "end": 144.114
        }
      ]
    }
  },
  "statutory": {
    "none": {
      "src": "./audio/recordings/statutory-none-0923.mp3",
      "duration": 145.373,
      "cues": [
        {
          "start": 0.324,
          "end": 8.015
        },
        {
          "start": 8.789,
          "end": 30.029
        },
        {
          "start": 30.029,
          "end": 40.609
        },
        {
          "start": 40.869,
          "end": 72.009
        },
        {
          "start": 72.589,
          "end": 97.129
        },
        {
          "start": 97.609,
          "end": 115.749
        },
        {
          "start": 116.269,
          "end": 145.209
        }
      ]
    },
    "procedural": {
      "src": "./audio/recordings/statutory-procedural-0923.mp3",
      "duration": 146.156,
      "cues": [
        {
          "start": 0.274,
          "end": 8.812
        },
        {
          "start": 9.572,
          "end": 30.812
        },
        {
          "start": 30.812,
          "end": 41.392
        },
        {
          "start": 41.652,
          "end": 72.792
        },
        {
          "start": 73.372,
          "end": 97.912
        },
        {
          "start": 98.392,
          "end": 116.532
        },
        {
          "start": 117.052,
          "end": 145.992
        }
      ]
    },
    "substantive": {
      "src": "./audio/recordings/statutory-substantive-0923.mp3",
      "duration": 148.093,
      "cues": [
        {
          "start": 0.261,
          "end": 10.769
        },
        {
          "start": 11.509,
          "end": 32.749
        },
        {
          "start": 32.749,
          "end": 43.329
        },
        {
          "start": 43.589,
          "end": 74.729
        },
        {
          "start": 75.309,
          "end": 99.849
        },
        {
          "start": 100.329,
          "end": 118.469
        },
        {
          "start": 118.989,
          "end": 147.929
        }
      ]
    },
    "decisional": {
      "src": "./audio/recordings/statutory-decisional-0923.mp3",
      "duration": 147.498,
      "cues": [
        {
          "start": 0.241,
          "end": 10.31
        },
        {
          "start": 10.914,
          "end": 32.154
        },
        {
          "start": 32.154,
          "end": 42.734
        },
        {
          "start": 42.994,
          "end": 74.134
        },
        {
          "start": 74.714,
          "end": 99.254
        },
        {
          "start": 99.734,
          "end": 117.874
        },
        {
          "start": 118.394,
          "end": 147.334
        }
      ]
    }
  }
};
