const assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const base=process.env.STUDY_TEST_URL||'http://127.0.0.1:8766';const dk='judicial_ai_responsibility_draft_v2',rk='judicial_ai_responsibility_prototype_records_v1';
(async()=>{const b=await chromium.launch({headless:true});try{
 // Recover an old active third tab without a lockout, preserve original assignment.
 const c=await b.newContext(),p=await c.newPage();await p.goto(base+'/?view=participant');
 const a=await p.evaluate(k=>{const a={...StudyCore.assignParticipant({practicingLawyer:'no',legalDegree:'no',litigationExperience:'no'},{choose:x=>x[0],sessionId:'LEGACY'}),version:'2.1.0'};localStorage.setItem(k,JSON.stringify({version:'2.1.0',epoch:localStorage.getItem('judicial_ai_responsibility_reset_epoch_v2'),assignment:a,step:'survey',activeDossierTab:'task',ranking:['judge','court'],rankingInitial:['judge','court'],reading:{task:{confirmed:true,reachedEnd:true}},replay:{version:'dialogue-2026-09-08-v1',mode:'stream',completed:true}}));return a;},dk);
 await p.reload();await p.locator('#role-dialog[open]').waitFor();assert.deepEqual(await p.evaluate(()=>state.assignment),a);assert.equal(await p.evaluate(()=>state.activeDossierTab),'overview');assert.equal(await p.locator('#updated-consent').isVisible(),true);assert.equal(await p.evaluate(()=>state.ranking.length),4);assert.equal(await p.evaluate(()=>state.replay.completed),false);
 // One missing case recording keeps both cases on identical text presentation.
 await p.route('**/audio-config.js*',r=>r.fulfill({contentType:'application/javascript',body:"window.STUDY_AUDIO_VERSION=StudyNarration.VERSION;window.STUDY_AUDIO={natural:'./natural.mp3',statutory:''};"}));await p.reload();assert.equal(await p.evaluate(()=>state.replay.mode),'text');
 // Media errors remain visible instead of being overwritten by the exposure ticker.
 await p.locator('#role-video').evaluate(v=>v.dispatchEvent(new Event('error')));await p.waitForTimeout(750);assert.match(await p.locator('#role-status').innerText(),/暂时无法播放/);
 // A current-version unsubmitted draft from the old role-only video must restart the current trial.
 await p.evaluate(k=>{const d=snapshot();d.version=StudyCore.VERSION;d.step='survey';d.orientation[d.session.caseOrder[d.session.caseIndex]]={version:'role-immersion-2026-09-16-v2',completed:true,videoCompleted:true,visibleMs:18000};d.reading=Object.fromEntries(['overview','evidence','task'].map(t=>[t,{reachedEnd:true,confirmed:true,visibleMs:6000}]));d.formValues={fairness:'7',involvement:'7'};d.replay={mode:'text',version:StudyNarration.VERSION,completed:true,textReachedEnd:true,textVisibleMs:40000};d.transcriptConfirmed=true;localStorage.setItem(k,JSON.stringify(d));},dk);
 await p.reload();await p.locator('#role-dialog[open]').waitFor();assert.equal(await p.evaluate(()=>state.step),'dossier');assert.equal(await p.evaluate(()=>state.formValues.fairness),undefined);assert.equal(await p.evaluate(()=>StudyCore.readingComplete(state.reading)),false);assert.equal(await p.evaluate(()=>state.orientation[state.caseType].version),'case-role-broll-2026-09-16-v5');assert.deepEqual(await p.evaluate(()=>state.assignment),a);
 await c.close();
 // Retain a completed old single-case answer while offering the second case.
 const c2=await b.newContext(),p2=await c2.newPage();await p2.goto(base+'/?view=participant');
 const old=await p2.evaluate(({dk,rk})=>{const a={...StudyCore.assignParticipant({practicingLawyer:'yes',legalDegree:'yes'},{choose:x=>x[0],sessionId:'OLD-ANSWER'}),version:'2.1.0'};const response={...a,ratings:{fairness:2},openResponse:'旧答卷',submittedAt:'2026-09-08T00:00:00Z'};localStorage.setItem(rk,JSON.stringify([response]));localStorage.setItem(dk,JSON.stringify({version:'2.1.0',epoch:localStorage.getItem('judicial_ai_responsibility_reset_epoch_v2'),assignment:a,step:'debrief',ranking:['judge','court'],rankingInitial:['judge','court'],response}));return response;},{dk,rk});await p2.reload();await p2.locator('#screen-between.active').waitFor();await p2.locator('#next-case').click();await p2.locator('#role-dialog[open]').waitFor();assert.equal(await p2.evaluate(()=>state.caseType),'statutory');assert.deepEqual(await p2.evaluate(()=>state.session.responses),[old]);assert.deepEqual(await p2.evaluate(k=>JSON.parse(localStorage.getItem(k)),rk),[old]);await c2.close();
 console.log('Passed: old assignment and answers preserved, old third-tab recovery, updated consent, shared text fallback and persistent video retry message.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
