const assert=require('node:assert/strict'),fs=require('node:fs/promises'),cp=require('node:child_process');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const base=process.env.STUDY_TEST_URL||'http://127.0.0.1:8765';
// A fixed pre-upgrade writer verifies compatibility with tabs opened before deployment.
const oldApp=cp.execFileSync('git',['show','70e834523f24808a7083d20ed21fb802357df761:app.js'],{encoding:'utf8'});
(async()=>{const browser=await chromium.launch({headless:true});try{
 const context=await browser.newContext(),old=await context.newPage();await old.route('**/app.js',r=>r.fulfill({contentType:'application/javascript',body:oldApp}));await old.goto(base+'/?view=participant');
 const response=await old.evaluate(()=>{const a=StudyCore.assignParticipant({practicingLawyer:'no',legalDegree:'no',litigationExperience:'no'},{choose:x=>x[0],sessionId:'UPGRADE'}),r={version:'2.1.0',sessionId:a.sessionId,role:a.role,condition:a.condition,caseType:a.caseType,ratings:{fairness:3},openResponse:'已提交首案',submittedAt:'2026-09-08T00:00:00Z'};localStorage.setItem(STORAGE_KEY,JSON.stringify([r]));localStorage.setItem(DRAFT_KEY,JSON.stringify({version:'2.1.0',epoch:'',assignment:a,step:'debrief',ranking:['judge','court'],rankingInitial:['judge','court'],response:r}));return r;});await old.reload();await old.locator('#screen-debrief.active').waitFor();
 const fresh=await context.newPage();await fresh.goto(base+'/?view=participant');await fresh.locator('#screen-between.active').waitFor();assert.deepEqual(await fresh.evaluate(()=>state.session.responses),[response]);
 const newEpoch=await fresh.evaluate(()=>storageEpoch);assert.notEqual(newEpoch,'');assert.equal(await old.evaluate(()=>currentEpoch()),false);
 await fresh.evaluate(()=>{state.session=SESSION.submit(SESSION.advance(state.session),{...state.response,caseType:'statutory',openResponse:'第二案独立回答'},state.assignment);state.response=state.session.responses[1];updateSavedResponse(SESSION.record(state.session,state.assignment));setStep('debrief');});
 const before=await fresh.evaluate(()=>localStorage.getItem(STORAGE_KEY));await old.locator('#retain-response').click();await old.evaluate(()=>saveDraft());assert.equal(await fresh.evaluate(()=>localStorage.getItem(STORAGE_KEY)),before,'old single-case writer cannot replace the two-case envelope');
 await fresh.reload();await fresh.locator('#screen-debrief.active').waitFor();assert.equal(await fresh.evaluate(()=>storageEpoch),newEpoch,'upgrade is idempotent');assert.equal(await fresh.evaluate(()=>state.session.responses.length),2);await context.close();
 for(const failAt of ['draft','epoch','finish']){
  const ctx=await browser.newContext(),p=await ctx.newPage();await p.route('**/app.js',r=>r.fulfill({contentType:'application/javascript',body:oldApp}));await p.goto(base+'/?view=participant');
  await p.evaluate(()=>{const assignment=StudyCore.assignParticipant({practicingLawyer:'no',legalDegree:'no',litigationExperience:'no'},{choose:x=>x[0],sessionId:'UPGRADE-FAIL'});localStorage.setItem(DRAFT_KEY,JSON.stringify({version:'2.1.0',epoch:'',assignment,step:'dossier',ranking:['judge','court'],rankingInitial:['judge','court'],formValues:{openResponse:'需要保留的草稿'},replay:{mode:'stream',version:StudyDialogue.VERSION,completed:false}}));});
  await p.unroute('**/app.js');await p.addInitScript(failAt=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){const match=failAt==='draft'?k==='judicial_ai_responsibility_draft_v2':failAt==='epoch'?k==='judicial_ai_responsibility_reset_epoch_v2':k==='judicial_ai_responsibility_protocol_v1'&&JSON.parse(v).phase==='complete';if(this===localStorage&&match&&!sessionStorage.getItem('failedOnce')){sessionStorage.setItem('failedOnce','yes');throw new DOMException('fixture quota','QuotaExceededError');}return original.call(this,k,v);};},failAt);
  await p.reload();assert.ok((await p.evaluate(()=>localStorage.getItem(DRAFT_KEY)))?.includes('需要保留的草稿'),'failed upgrade must keep the original draft');
  await p.reload();await p.locator('#screen-dossier.active').waitFor();assert.equal(await p.locator('#open-response').inputValue(),'需要保留的草稿','refresh resumes an interrupted upgrade');await ctx.close();
 }
 console.log('Passed: protocol upgrade migrates the old draft, retires already-open single-case writers and preserves both answers across refresh.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
