const assert=require('node:assert/strict');const fs=require('node:fs/promises');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const base=process.env.STUDY_TEST_URL||'http://127.0.0.1:8765';
const recordsKey='judicial_ai_responsibility_prototype_records_v1',draftKey='judicial_ai_responsibility_draft_v2_preview_lawyer_none_natural';
function wav(){const size=8000*2*2,b=Buffer.alloc(44+size);b.write('RIFF');b.writeUInt32LE(36+size,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(size,40);return b;}
async function read(page){for(const tab of ['overview','evidence','task']){await page.locator(`[data-tab=${tab}]`).click();await page.locator('#dossier-content').evaluate(el=>{el.scrollTop=el.scrollHeight;el.dispatchEvent(new Event('scroll'));});await page.locator('#dossier-confirm').check();}await page.locator('#to-replay').click();}
async function finishAudio(page){await page.locator('#playback-toggle').click();await page.locator('#transcript-confirm:not([disabled])').waitFor();await page.locator('#transcript-confirm').check();await page.locator('#to-decision').click();await page.locator('#to-survey').click();}
async function rate(page,value){await page.locator('[name=manipulationCheck]').selectOption('none');await page.locator('[name=finalSigner]').selectOption('judge');await page.locator('#ranking-mode').selectOption('unsure');for(const name of ['fairness','control','clarity','judgeOwnership','legitimacy','acceptance'])await page.locator(`[name=${name}][value="${value}"]`).check();await page.locator('[name=honestConfirm]').check();}
(async()=>{const browser=await chromium.launch({headless:true});try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.recognizers=[];window.SpeechRecognition=class{constructor(){window.recognizers.push(this);}start(){this.onstart?.();}stop(){this.onend?.();}abort(){this.onend?.();}};});
 await page.route('**/audio-config.js*',route=>route.fulfill({contentType:'application/javascript',body:'window.STUDY_AUDIO_VERSION=StudyDialogue.VERSION;window.STUDY_AUDIO='+JSON.stringify(Object.fromEntries(['natural','statutory'].map(k=>[k,Object.fromEntries(['none','procedural','substantive','decisional'].map(c=>[c,`./audio/recordings/${k}-${c}.wav`]))])))+';'}));
 await page.route('**/audio/recordings/*.wav',route=>{const b=wav(),range=route.request().headers().range?.match(/^bytes=(\d+)-(\d*)$/);if(!range)return route.fulfill({contentType:'audio/wav',headers:{'Accept-Ranges':'bytes'},body:b});const start=Number(range[1]),end=range[2]?Math.min(Number(range[2]),b.length-1):b.length-1;return route.fulfill({status:206,contentType:'audio/wav',headers:{'Accept-Ranges':'bytes','Content-Range':`bytes ${start}-${end}/${b.length}`},body:b.subarray(start,end+1)});});
 await page.goto(base+'/?view=participant&preview=1&role=lawyer&condition=none&case=natural');await page.locator('#consent-checkbox').check();await page.locator('#start-study').click();
 const assignment=await page.evaluate(()=>state.assignment);await read(page);await finishAudio(page);await rate(page,'3');
 await page.locator('#speech-start').click();await page.evaluate(()=>{window.lateResult=window.recognizers[0].onresult;lateResult({resultIndex:0,results:[{0:{transcript:'第一案语音回答'},isFinal:true,length:1}]});});await page.locator('#speech-stop').click();await page.locator('#open-response-confirm').check();
 const oldDraft=await page.evaluate(k=>sessionStorage.getItem(k),draftKey);
 await page.locator('#submit-evaluation').click();await page.locator('#screen-between.active').waitFor();
 const first=await page.evaluate(k=>JSON.parse(localStorage.getItem(k))[0].responses[0],recordsKey);assert.equal(first.speech.attempts,1);assert.equal(first.audio.completed,true);
 await page.screenshot({path:'../../work/two-case-transition.png',fullPage:true,animations:'disabled'});
 // Recover the durable first answer even if its following draft save was lost.
 await page.evaluate(({k,v})=>sessionStorage.setItem(k,v),{k:draftKey,v:oldDraft});await page.reload();await page.locator('#screen-between.active').waitFor();assert.deepEqual(await page.evaluate(()=>state.session.responses),[first]);
 await page.locator('#next-case').click();await page.locator('#screen-dossier.active').waitFor();assert.deepEqual(await page.evaluate(()=>state.assignment),assignment);assert.equal(await page.evaluate(()=>state.caseType),'statutory');
 assert.equal(await page.locator('#reading-progress').innerText(),'已完成 0 / 3 栏');assert.equal(await page.locator('#open-response').inputValue(),'');assert.equal(await page.evaluate(()=>speech.getMetadata().attempts),0);assert.equal(await page.locator('#transcript-confirm').isDisabled(),true);
 await read(page);assert.equal(await page.evaluate(()=>state.audio.completed),false);assert.equal(await page.evaluate(()=>state.audio.started),false);assert.equal(await page.locator('#judgment-audio').evaluate(a=>a.currentTime),0);assert.equal(await page.locator('#chat-messages').innerText(),'');
 await page.screenshot({path:'../../work/two-case-second-audio.png',fullPage:true,animations:'disabled'});
 await page.reload();await page.locator('#screen-replay.active').waitFor();await finishAudio(page);await rate(page,'7');
 await page.locator('#submit-evaluation').click();await page.locator('#screen-debrief.active').waitFor();
 let record=await page.evaluate(k=>JSON.parse(localStorage.getItem(k))[0],recordsKey);assert.equal(record.completed,true);assert.deepEqual(record.responses[0],first);assert.equal(record.responses[1].ratings.fairness,7);assert.equal(record.responses[1].openResponse,'');assert.equal(record.responses[1].speech.attempts,0);assert.equal(record.responses[1].audio.completed,true);
 assert.equal(await page.evaluate(()=>{try{updateSavedResponse({...SESSION.record(state.session,state.assignment),responses:[]});return false;}catch{return true;}}),true,'stale partial data cannot overwrite both answers');
 await page.locator('#retain-response').click();await page.reload();await page.locator('#screen-debrief.active').waitFor();
 const dl=page.waitForEvent('download');await page.locator('#download-response').click();const downloaded=await dl;record=JSON.parse(await fs.readFile(await downloaded.path(),'utf8'));assert.equal(record.responses.length,2);assert.equal(record.retained,true);assert.deepEqual(errors,[]);await context.close();
 // A previously submitted single-case draft offers the missing case, preserving its answer.
 const legacyContext=await browser.newContext(),legacyPage=await legacyContext.newPage();await legacyPage.goto(base+'/?view=participant');
 const old=await legacyPage.evaluate(k=>{const assignment=StudyCore.assignParticipant({practicingLawyer:'no',legalDegree:'no',litigationExperience:'no'},{choose:x=>x[0],sessionId:'OLD-CONTINUE'});const response={...assignment,ratings:{fairness:2},openResponse:'原先单案回答',submittedAt:'2026-09-08T00:00:00Z'};localStorage.setItem(k,JSON.stringify([response]));localStorage.setItem('judicial_ai_responsibility_draft_v2',JSON.stringify({version:'2.1.0',epoch:localStorage.getItem('judicial_ai_responsibility_reset_epoch_v2')||'',assignment,step:'debrief',ranking:['judge','court'],rankingInitial:['judge','court'],response}));return response;},recordsKey);
 await legacyPage.reload();await legacyPage.locator('#screen-between.active').waitFor();await legacyPage.locator('#next-case').click();await legacyPage.reload();await legacyPage.locator('#screen-dossier.active').waitFor();assert.equal(await legacyPage.evaluate(()=>state.caseType),'statutory');assert.deepEqual(await legacyPage.evaluate(()=>state.session.responses),[old]);assert.deepEqual(await legacyPage.evaluate(k=>JSON.parse(localStorage.getItem(k)),recordsKey),[old]);await legacyContext.close();
 console.log('Passed: audio and speech isolation across two cases, first-answer recovery, second-case refresh, independent answers, final retention/JSON, stale overwrite prevention, legacy continuation and mobile screenshots.');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
