#!/usr/bin/env python3
"""Rebuild the eight approved recordings from local sources (requires ffmpeg/ffprobe).
Usage: python3 scripts/assemble-condition-audio.py INTRO NATURAL STATUTORY
Source files stay outside the repository; only hashes and timing are recorded.
"""
import hashlib, json, pathlib, shutil, subprocess, sys, tempfile
ROOT = pathlib.Path(__file__).resolve().parents[1]
RATE = 24000
CUTS = [0, 8.289, 17.361, 28.370, 38.784]  # Midpoints of inter-condition silence.
KEYS = ['none', 'procedural', 'substantive', 'decisional']
INTRO_CUES = [(0.324, 8.015), (8.563, 17.101), (17.622, 28.130), (28.611, 38.680)]
BODY_CUES = {
 'natural': [(0,31.18),(31.18,63.04),(63.54,91.62),(91.62,112.66),(112.66,133.20)],
 'statutory': [(0,21.24),(21.24,31.82),(32.08,63.22),(63.80,88.34),(88.82,106.96),(107.48,136.42)]
}
VERSION = 'condition-narration-2026-09-23-v1'

def main():
 if len(sys.argv) != 4:
  raise SystemExit(__doc__)
 paths = [pathlib.Path(p).resolve(strict=True) for p in sys.argv[1:]]
 ffmpeg, ffprobe = shutil.which('ffmpeg'), shutil.which('ffprobe')
 if not ffmpeg or not ffprobe:
  raise SystemExit('ffmpeg and ffprobe are required')
 def decode(p):
  return subprocess.check_output([ffmpeg,'-v','error','-i',str(p),'-f','s16le','-ac','1','-ar',str(RATE),'-'])
 intro = decode(paths[0])
 bodies = dict(zip(BODY_CUES, map(decode,paths[1:])))
 audio_dir = ROOT/'audio/recordings'
 audio_dir.mkdir(parents=True,exist_ok=True)
 config = {c:{} for c in BODY_CUES}
 with tempfile.TemporaryDirectory() as td:
  for case, body in bodies.items():
   for i, key in enumerate(KEYS):
    start, end = [round(t*RATE) for t in CUTS[i:i+2]]
    segment = intro[start*2:end*2]
    gap = bytes(round(0.5*RATE)*2)
    offset = (len(segment)+len(gap))/(2*RATE)
    pcm = pathlib.Path(td)/'joined.pcm'
    pcm.write_bytes(segment+gap+body)
    target = audio_dir/f'{case}-{key}-0923.mp3'
    subprocess.run([ffmpeg,'-v','error','-y','-f','s16le','-ar',str(RATE),'-ac','1','-i',str(pcm),'-c:a','libmp3lame','-b:a','96k','-map_metadata','-1',str(target)],check=True)
    duration = float(subprocess.check_output([ffprobe,'-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',str(target)]))
    cues = [(INTRO_CUES[i][0]-CUTS[i],INTRO_CUES[i][1]-CUTS[i])] + [(offset+s,offset+e) for s,e in BODY_CUES[case]]
    config[case][key] = dict(src='./'+str(target.relative_to(ROOT)),duration=duration,cues=[dict(start=round(s,4),end=round(e,4)) for s,e in cues])
 (ROOT/'audio-config.js').write_text('/* Generated by scripts/assemble-condition-audio.py. Eight conditions enable together. */\nwindow.STUDY_AUDIO_VERSION='+json.dumps(VERSION)+';\nwindow.STUDY_AUDIO='+json.dumps(config,ensure_ascii=False,indent=2)+';\n')
 manifest = dict(version=VERSION,sources={k:dict(filename=p.name,sha256=hashlib.sha256(p.read_bytes()).hexdigest()) for k,p in zip(['intro','natural','statutory'],paths)},cutSeconds=CUTS,gapSeconds=0.5,sampleRate=RATE,timingMethod='Local ASR paragraph boundaries; intro cuts at measured silence midpoints. Paragraph text reveals linearly within each cue, not word-level forced alignment.',gain='Unchanged: original means -17.2/-17.5 dBFS and intro -17.7 dBFS.',outputs={v['src']:dict(sha256=hashlib.sha256((ROOT/v['src']).read_bytes()).hexdigest(),duration=v['duration']) for cases in config.values() for v in cases.values()})
 (ROOT/'docs/audio-production-0923.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
 print('Generated eight recordings and matching timing configuration.')
if __name__ == '__main__':
 main()
